### ISSUE TITLE
available tasks vs tasks?

### ISSUE THREAD

**Issue by loschorts** [nmatte/TaskLion#1]
i may be misunderstanding, but is there a reason tasks can't hold body, etc, along with a column for available? what is the purpose of the separate available tasks table?

**Comment by nmatte** [comment]
A `Task` is the general information about a task. Some of them require a car, for instance, which would be present in the `details` json column. It's not connected to a `Tasker`.

`AvailableTask`s are the tasks that a Tasker has decided to offer. They need to provide a rate, a blurb (i.e. why you should hire them for that task), and their available schedule for that task. The `available_tasks` table joins `Taskers` and `Tasks`. Does that make sense?
